version: '3.3'

services:
  bot:
    restart: always
    build:
      context: .
    entrypoint:
      - /usr/app/bot_entrypoint.sh
    volumes:
      - ./:/usr/app/
    depends_on:
      - bot_db
    env_file:
      - .env.prod

  schedule:
    restart: always
    build:
      context: .
    entrypoint:
      - /usr/app/scheduler.sh
    volumes:
      - ./:/usr/app/
    depends_on:
      - bot_db
    env_file:
      - .env.prod

  bot_db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    ports:
      - 5432:5432

volumes:
  postgres_data: