"""add unique field in table news_messages

Revision ID: 0dd2287b640d
Revises: 5a013f217707
Create Date: 2022-05-21 13:35:52.809083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dd2287b640d'
down_revision = '5a013f217707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'news_messages', ['created_at'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news_messages', type_='unique')
    # ### end Alembic commands ###
