"""add time fields in user table

Revision ID: 560ddd0d22a0
Revises: 2636a77af062
Create Date: 2022-05-24 13:21:31.507329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560ddd0d22a0'
down_revision = '2636a77af062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('timezone', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('time_mailing', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'time_mailing')
    op.drop_column('user', 'timezone')
    # ### end Alembic commands ###
