"""remove column

Revision ID: bfb7bd0a9591
Revises: f6d3737aa66f
Create Date: 2022-05-19 21:28:37.454284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfb7bd0a9591'
down_revision = 'f6d3737aa66f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
